config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :ports
  
  devise_scope :user do
    authenticated  do
      root to: 'visitante#index'
    end

    unauthenticated do
      root to: 'users/sessions#new', as: 'unauthenticated_root'
    end
  end  
  
  resources :visitante
  
  post 'novoUsuario',  to: 'users#add_user'
  get  'novoUsuario',  to: 'users#new'

  get 'liberarPortas' => 'ports#liberarPortas', :as => :liberarPortas
  get 'fecharPortas'  => 'ports#fecharPortas',  :as => :fecharPortas
  get 'estadoPortas'  => 'ports#estadoPortas',  :as => :estadoPortas
  
  

  

end

app/models/port.rb
class Port < ActiveRecord::Base
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]

  include HTTParty
  
  # GET /ports
  # GET /ports.json
  def index
    @ports = Port.all
  end

  # GET /ports/1
  # GET /ports/1.json
  def show
  end

  # GET /ports/new
  def new
    @port = Port.new
  end

  # GET /ports/1/edit
  def edit
  end

  # POST /ports
  # POST /ports.json
  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to ports_path, notice: 'Port was successfully created.' }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ports/1
  # PATCH/PUT /ports/1.json
  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to ports_path, notice: 'Port was successfully updated.' }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1
  # DELETE /ports/1.json
  def destroy
    @port.destroy
    respond_to do |format|
      format.html { redirect_to ports_url, notice: 'Port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def liberarPortas
    
    @response = HTTParty.get("http://#{params[:ip]}/assimnao123/abrir")
      
    redirect_to "/" 
  end
  
  def fecharPortas
    
    @response = HTTParty.get("http://#{params[:ip]}/assimnao123/fechar")
      
    redirect_to "/" 
  end
  
  def estadoPortas
    @response = HTTParty.get("http://#{params[:ip]}/estado")
    render :text => @response
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port
      @port = Port.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def port_params
      params.require(:port).permit(:ip, :descricao)
    end
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/views/ports/_form.html.erb
<div class="col-sm-6 centro" style="margin-top: 10%;">
  		<div class="featured-box featured-box-primary mt-xlg">
	  		<div class="box-content">
          <%= form_for(@port) do |f| %>
          <h4 class="heading-primary text-uppercase mb-md head-label">Informe os dados abaixo</h4>
  	  		<form action="/" id="frmVisitante" method="post">
         
          <% if @port.errors.any? %>
            <div class="alert alert-danger">
              <h2>Oops! campos com erro:</h2>
              <% @port.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </div>
          <% end %>
        
        <div class="row">
					<div class="form-group">
						<div class="col-md-12 campo-cadastro">
							<a class="label-cadastro">IP da porta</a>
							 <%= f.text_field :ip, :autofocus => true, class: 'form-control input-lg' %>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="form-group">
						<div class="col-md-12 campo-cadastro">
							<a class="label-cadastro">Descrição da porta</a>
							 <%= f.text_field :descricao, :autofocus => true, class: 'form-control input-lg' %>
						</div>
					</div>
				</div>
				
				<div class="row">
				  <div class="col-md-6 centro">
						<input type="submit" value="Cadastrar" class="btn btn-primary mb-xl btn-cadastro" data-loading-text="Aguarde...">
					</div>  
				</div>
				
				</form>
      <% end %>
    </div>
  </div>
</div>

app/views/ports/edit.html.erb
<h1>Editing Port</h1>

<%= render 'form' %>

<%= link_to 'Voltar', ports_path %>

app/views/ports/index.html.erb
<div class="centro-table" style="margin-top: 10%;">
  <div class="container-form">
    <div class="row">
    <div class="col-lg-12">
          <div class="panel panel-default">
              <div class="panel-heading">
                  Portas Cadastradas
                  <div class="btn btn-success"><%= link_to 'Nova porta', new_port_path %></div>
              </div>
              <!-- /.panel-heading -->
              <div class="panel-body">
                  <table width="100%" class="table table-striped table-bordered table-hover responsive" id="dataTables-portas">
                      <thead>
                          <tr>
                              <th>Ip</th>
                              <th>Descricao</th>
                              <th colspan="2"></th>
                          </tr>
                      </thead>
                      <tbody>
                          <% @ports.each do |port| %>
                          <tr class="gradeA odd" role="row">
                            
                            <td class="sorting_1"><%= port.ip %></td>
                            <td><%= port.descricao %></td>
                            <td><%= link_to 'Editar', edit_port_path(port) %></td>
                            <td><%= link_to 'Apagar', port, method: :delete, data: { confirm: 'Apagar porta?' } %></td>
                          </tr>
                          <% end %>
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>  
  </div>
</div>


<script type="text/javascript" charset="utf8" src="/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="/js/dataTables.responsive.js"></script>
<script type="text/javascript" charset="utf8" src="/js/dataTables.bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
        $('#dataTables-portas').DataTable({
            responsive: true
        });
    });
</script>

<script type="text/javascript" charset="utf8" src="/js/bootstrap.min.js"></script>

app/views/ports/new.html.erb
<h1>New Port</h1>

<%= render 'form' %>

<%= link_to 'Back', ports_path %>

app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @port.ip %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @port.descricao %>
</p>

<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>