config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :ports
  
  devise_scope :user do
    authenticated  do
      root to: 'visitante#index'
    end

    unauthenticated do
      root to: 'users/sessions#new', as: 'unauthenticated_root'
    end
  end  
  
  resources :visitante
  
  post 'novoUsuario',  to: 'users#add_user'
  get  'novoUsuario',  to: 'users#new'

  get 'liberarPortas' => 'ports#liberarPortas', :as => :liberarPortas
  get 'fecharPortas'  => 'ports#fecharPortas',  :as => :fecharPortas
  get 'estadoPortas'  => 'ports#estadoPortas',  :as => :estadoPortas
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:guest, :student, :admin]
  after_initialize :set_default_role, :if => :new_record?
  
  def set_default_role
    self.role ||= :student
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  
  def create
    super #Nothing special here.
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def sign_up(resource_name, resource)
    true
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    
    
    #render :text => params[:user][:ports_id].inspect
   
    user = User.find_by_sql ["select * from users where nome = ?",params[:user][:nome]]
    
    # render :text => params[:user][:ports_id].inspect
    
    
    
    params[:user][:ports_id].each do |port, user_id|
     
      if (port != "") then
        
        verificaPermissao = Permition.find_by_sql ["Select id from permitions where port_id = ? and user_id = ?", port, user[0].id]
        
        if (verificaPermissao.empty?) then
          
          permition = Permition.new
          permition.port_id = port
          permition.user_id = user[0].id
          permition.save!
        end
      end
    end
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_user
    @user = User.new(user_params)
     if @user.save!
       redirect_to root_path
     end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :email, :password, :password_confirmation, :ports_id => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-sm-6 centro" style="margin-top: 10%;">
	<div class="featured-box featured-box-primary mt-xlg">
		<div class="box-content">
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> Este usuário não pode ser salvo:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <div class="row">
					<div class="form-group">
						<div class="col-md-12 campo-cadastro">
							<a class="label-cadastro">Nome</a>
							 <%= f.text_field :nome, :autofocus => true, class: 'form-control input-lg' %>
						</div>
					</div>
				</div>
        
        <%= f.collection_check_boxes(:ports_id, Port.all, :id, :ip) do |b| %>
          <div class="row">
            <%= b.label(class: "check_box") do %>
              <div class="col-md-4">
                <%= b.check_box(class: "check_box") %>
              </div>
        
              <div class="col-md-8">
                <%= b.object.descricao %>
              </div>       
            <% end %>
          </div>
        <% end %>
        
        
    <div class="row">
		  <div class="col-md-6 centro">
				<input type="submit" value="Salvar" class="btn btn-primary mb-xl btn-cadastro" data-loading-text="Aguarde...">
			</div>  
		</div>
        
       
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Voltar', users_path %>

app/views/users/index.html.erb
<div class="centro-table" style="margin-top: 10%;">
  <div class="container-form">
    <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Usuários Cadastradas
            <!-- <div class="btn btn-success"><%= link_to 'Novo Usuário', novoUsuario_path %></div> -->
          </div>
            <!-- /.panel-heading -->
          <div class="panel-body">
            <table width="100%" class="table table-striped table-bordered table-hover responsive" id="dataTables-users">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                    <tr class="gradeA odd" role="row">
                      
                      <td class="sorting_1"><%= user.nome %></td>
                      <td><%= link_to 'Editar', edit_user_path(user) %></td>
                      <td><%= link_to 'Apagar', user, method: :delete, data: { confirm: 'Apagar usuário?' } %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>  
  </div>
</div>


<script type="text/javascript" charset="utf8" src="/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="/js/dataTables.responsive.js"></script>
<script type="text/javascript" charset="utf8" src="/js/dataTables.bootstrap.min.js"></script>
<script>
  $(document).ready(function() {
        $('#dataTables-users').DataTable({
            responsive: true
        });
    });
</script>

<script type="text/javascript" charset="utf8" src="/js/bootstrap.min.js"></script>
    

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/novoUsuario.html.erb
<%= form_for User.new , :url => {:action => "add_user"} do |user| %>
  <%=user.email_field :email%>
  <%=user.password_field :password%>
  <%=user.password_field :password_confirmation%>

  <%=user.submit 'add'%>
<%end%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>